library(ggthemes)

# ggplot2和ggthemes提供的30主题
ggplot2_themes <- c(
  "gray",
  "bw",
  "linedraw",
  "light",
  "dark",
  "minimal",
  "classic",
  "void",
  "base",
  "calc",
  "clean",
  "economist",
  "economist_white",
  "excel",
  "excel_new",
  "few",
  "fivethirtyeight",
  "foundation",
  "gdocs",
  "hc",
  "igray",
  "map",
  "pander",
  "par",
  "solarized",
  "solarized_2",
  "solid",
  "stata",
  "tufte",
  "wsj"
)

# 添加主题
add_theme <- function(p, vis_theme, vis_font_size, vis_font_family="") {
  switch(vis_theme,
         gray = p + theme_gray(base_family=vis_font_family, base_size=vis_font_size),
         bw = p + theme_bw(base_family=vis_font_family, base_size=vis_font_size),
         linedraw = p + theme_linedraw(base_family=vis_font_family, base_size=vis_font_size),
         light = p + theme_light(base_family=vis_font_family, base_size=vis_font_size),
         dark = p + theme_dark(base_family=vis_font_family, base_size=vis_font_size),
         minimal = p + theme_minimal(base_family=vis_font_family, base_size=vis_font_size),
         classic = p + theme_classic(base_family=vis_font_family, base_size=vis_font_size),
         void = p + theme_void(base_family=vis_font_family, base_size=vis_font_size),
         base = p + theme_base(base_family=vis_font_family, base_size=vis_font_size),
         calc = p + theme_calc(base_family=vis_font_family, base_size=vis_font_size),
         clean = p + theme_clean(base_family=vis_font_family, base_size=vis_font_size),
         economist = p + theme_economist(base_family=vis_font_family, base_size=vis_font_size),
         economist_white = p + theme_economist_white(base_family=vis_font_family, base_size=vis_font_size),
         excel = p + theme_excel(base_family=vis_font_family, base_size=vis_font_size),
         excel_new = p + theme_excel_new(base_family=vis_font_family, base_size=vis_font_size),
         few = p + theme_few(base_family=vis_font_family, base_size=vis_font_size),
         fivethirtyeight = p + theme_fivethirtyeight(base_family=vis_font_family, base_size=vis_font_size),
         foundation = p + theme_foundation(base_family=vis_font_family, base_size=vis_font_size),
         gdocs = p + theme_gdocs(base_family=vis_font_family, base_size=vis_font_size),
         hc = p + theme_hc(base_family=vis_font_family, base_size=vis_font_size),
         igray = p + theme_igray(base_family=vis_font_family, base_size=vis_font_size),
         map = p + theme_map(base_family=vis_font_family, base_size=vis_font_size),
         pander = p + theme_pander(base_family=vis_font_family, base_size=vis_font_size),
         par = p + theme_par(base_family=vis_font_family, base_size=vis_font_size),
         solarized = p + theme_solarized(base_family=vis_font_family, base_size=vis_font_size),
         solarized_2 = p + theme_solarized_2(base_family=vis_font_family, base_size=vis_font_size),
         solid = p + theme_solid(base_family=vis_font_family, base_size=vis_font_size),
         stata = p + theme_stata(base_family=vis_font_family, base_size=vis_font_size),
         tufte = p + theme_tufte(base_family=vis_font_family, base_size=vis_font_size),
         wsj = p + theme_wsj(base_family=vis_font_family, base_size=vis_font_size, title_family=""),
  )
}
